locallibrary/catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
		#path('',views.index,name='index')
		url(r'^$',views.index,name='index'),
		url(r"^books/$",views.BookListView.as_view(), name = 'books'),
		url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name = 'book-detail'),
		url(r'^author/$',views.AuthorListView.as_view(), name = 'authors'),
		url(r'^author/(?P<pk>\d+)$',views.AuthorDetailView.as_view(), name = 'author-detail'),
		url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(),name='my-borrowed'),
		url(r'^borrowed/$',views.LoanedBooksAllListView.as_view(), name = 'all-borrowed'),
		url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
		

]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/',permanent = True)),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += [path('accounts/',include('django.contrib.auth.urls')),

]

locallibrary/catalog/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User 
from datetime import date





class Genre(models.Model):
	name = models.CharField(max_length=200, help_text = "Enter a book genre like Scince Fiction.")

	def __str__(self):
		return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
	title = models.CharField(max_length = 80, help_text = "Title of your book")
	
	author = models.ForeignKey('Author', on_delete = models.SET_NULL, null = True)
	summary = models.TextField(max_length = 1000)
	isbn = models.CharField('ISBN', max_length = 13)
	genre = models.ManyToManyField(Genre, help_text = "select a genre of book")
	language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

	def __str__(self):

		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		return ', '.join([genre.name for genre in self.genre.all()[:3]])
	display_genre.short_discription = 'Genre'

	class Meta:
		ordering = ["title"]

class BookInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4,help_text="Unique ID for this particular book across whole library")
	
	book = models.ForeignKey('Book', on_delete = models.SET_NULL, null = True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null = True, blank = True)
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	LOAN_STATUS = (
			('m','Maintenance'),
			('o','On loan'),
			('a', 'Available'),
			('r', 'Reserved'),

		)

	status = models.CharField(max_length=1, choices = LOAN_STATUS, blank = True, default='m', help_text='Book availability')

	class Meta:
		ordering = ["due_back"]
		permissions = (("can_mark_returned","Set book as returned"),)

	def __str__(self):
		return '%s (%s)'%(self.id, self.book.title)

	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

locallibrary/catalog/views.py
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from .forms import RenewBookForm


def index(request):
    num_books = Book.objects.all().count()     
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()
    num_authors=Author.objects.count()
    num_genre = Genre.objects.all().count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    restore_visits_time = request.session.set_expiry(0) 

    


    return render(request, 'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors,'num_genre':num_genre,
        'num_visits':num_visits

        },
     )
 
@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk = pk)

    #Если данный запрос типа POST тогда
    if request.method == 'POST':
        # Создаем экземпляр формы и заполняем данными из запроса (связывание, binding):
        form = RenewBookForm(request.POST)

        # Проверка валидности данных формы:
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse('all-borrowed'))


    # Если это GET (или какой-либо еще), создать форму по умолчанию.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date':proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html',{'form':form, 'bookinst':book_inst})




class BookListView(generic.ListView):
    model = Book
    paginate_by = 2

class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request,pk):
        try:
            book_id = Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404("book doesnt exist")

        return render(request,'catalog/book_detail.html',context={'book':book_id,})

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower = self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    permission_required = 'catalog.can_mark_returned'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  
   {% block title %}<title>Local Library</title> {% endblock %}
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>


<body>
 
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <hr>
          <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
          {% if user.is_authenticated %}
            <li>User: {{user.get_username}}</li>
            <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>  
          {% endif %}
          
          <hr>
          {% if user.is_staff %}
          <li>Staff</li>
          <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
          {% endif %}
          
         
        </ul>

        {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %}{% endblock %}

        {% block pagination %}
          {% if is_paginated %}
              <div class="pagination">
                  <span class="page-links">
                    {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                  </span>
              </div>
          {% endif %}
        {% endblock %} 

      </div>
    </div>

  </div>
 
  
  
 
 






</body>
</html>

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name}} {{author.last_name }}</h1>
  <p><strong>Date of bitrth:</strong> {{ author.date_of_birth }}</p> 
  <p><strong>Date of death:</strong> {% if author.date_of_death %}{{ author.date_of_death }}{% else %} Still alive {% endif %}</p>  
  
  <div style="margin-left:100px;margin-top:50px">
    <div class='books'>
      {% if author.book_set.all %}
      <ul>
        {% for book in author.book_set.all %}
        <li>
          <a href="{% url 'book-detail' book.pk %}">{{ book }}</a> ({{book.bookinstance_set.all.count}})
          <p>{{book.summary}}</p>
        </li>
        {% endfor %}

      </ul>
      {% else %}
      <p>There are no books in the library</p>
      {% endif %}
    
    </div>
  


  </div>



{% endblock %}

  

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}


{% block content %}
	<h1>Authors list</h1>

	{% if author_list %}
	<ul>
		{% for author in author_list %}
		<li>
			<a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a> 
			({{author.date_of_birth}} - {% if author.date_of_death %}{{ author.date_of_death }}{% else %} Still alive {% endif %})
		</li>
		{% endfor %}

	</ul>
	{% else %}
	<p>There no authors in list</p>
	{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}


{% block content %}
	<h1>Book list</h1>

	{% if book_list %}
	<ul>
		{% for book in book_list %}
		<li>
			<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
		</li>
		{% endfor %}

	</ul>
	{% else %}
	<p>There are no books in the library</p>
	{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

	<h1>Renew: {{ bookinst.book.title }}</h1>
	<p>Borrower: {{bookinst.borrower}}</p>
	<p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form }}
		</table>
		<input type="submit" value="Submit"/>

	</form>		

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>All Borrowed Books</h1>
	{% if bookinstance_list %}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>({{ bookinst.due_back }}){% if user.is_staff %}- {{bookinst.borrower}}{% endif %} 	
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no books borrowed</p>
	{% endif %}

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Borrowed Books</h1>

	{% if bookinstance_list %}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>({{ bookinst.due_back }})
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no books borrowed</p>
	{% endif %}

{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}


{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Genres:</strong> {{ num_genre }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

{% block title %} <title>MyLocal Library</title> {% endblock %}